<table class="table table-bordered" width="100%">
    <thead>
    <tr>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Họ và tên</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Mã đoàn viên</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Ngày sinh</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Giới tính</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Chức vụ</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Nhiệm kỳ</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Đối tượng quản lý</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Đơn vị</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Khối đối tượng</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Dân tộc</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Tôn giáo</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Tình trạng hôn nhân</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Ngày vào đoàn</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Quê quán - Tỉnh</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Quê quán - Quận/huyện</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Quê quán - Xã/phường</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Quê quán - Thôn,bản, TDP</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Nơi ở hiện nay - Tỉnh</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Nơi ở hiện nay - Quận/huyện</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Nơi ở hiện nay - Xã phường</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Nơi ở hiện nay - Thôn, bản, TDP</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Trình độ</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Chính trị</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Tin học</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Ngoại ngữ</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Học vấn</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Đảng viên</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Ngày vào đảng</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Trưởng thành đoàn</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Năm trưởng thành đoàn</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Chuyển đến</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Lý do chuyển đến</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Ngày chuyển đến</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Chuyển đi</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Lý do chuyển đi</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Ngày chuyển đi</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Đi làm ăn xa</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Lý do xóa tên</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Đánh giá đoàn viên</th>
        <th style="border: 1px solid #000000; border-collapse: collapse; ">Năm đánh giá</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Doãn Việt Long</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234566</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nữ</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/201</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Khá</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2018</td>
    </tr>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Vũ Hoàng Linh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234565</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>

        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nam</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Khá</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2018</td>
    </tr>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nguyễn Việt Long</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234564</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>

        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nữ</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Có</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung bình</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2018</td>
    </tr>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nguyễn Minh Anh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234563</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>

        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nam</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Có</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung bình</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2018</td>
    </tr>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Doãn Việt Dung</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234562</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>

        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nam</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Có</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Khá</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2018</td>
    </tr>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Vũ Việt Dung</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234561</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>

        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nam</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Có</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Khá</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2018</td>
    </tr>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nguyễn Thị Dung</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234560</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>

        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nam</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Có</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Có</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Khá</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2018</td>
    </tr>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Doãn Việt Long</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234569</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>

        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nữ</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Có</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Khá</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2018</td>
    </tr>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Vũ Minh Long</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234568</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>

        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nam</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Có</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Khá</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2018</td>
    </tr>
    <tr>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Doãn Việt Linh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">1234567</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>

        <td style="border: 1px solid #000000; border-collapse: collapse; ">Nữ</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2000-2010</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn trường THPT Yên Dũng Số 1</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đoàn viên khối trường học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Kinh</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Độc thân</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">11/11/2012</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Bắc Giang</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Đại học</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Trung cấp</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">B2</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">12</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Không</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Có</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; "></td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">Xuất sắc</td>
        <td style="border: 1px solid #000000; border-collapse: collapse; ">2017</td>
    </tr>
    </tbody>
</table>